### ISSUE TITLE
Adding new tasks

### ISSUE THREAD

**Issue by arturohernandez10** [XinyuanWangCS/PromptAgent#1]
I like your paper, and would be willing to help add more tasks. Could you please just outline on what are some initial considerations in how to extend PromptAgent for other tasks? I will be looking at the code and add some considerations here as well.

I am hoping the cost of creating new prompts is not too high.

**Comment by XinyuanWangCS** [comment]
Hi,

Thanks for liking our paper. The cost of adding new tasks depends on what
type the new task is. If the new task is selection questions, it will be
relatively easy and you can check the task.py files in src/tasks. You
should consider loading your dataset (split your dataset into train/test
before, if you don't want random split), process the input question and
extract the output answer. You can think of a better initial prompt than
"Let's solve the problem" according to your task. The PromptAgent learns
from example by comparing the output and the label, so if your task is not
selection problems, specific metric calculation methods should be developed
accordingly.

The code of PromptAgent is still under polishment. Feel free to email me if
you have any questions.

Best,
Xinyuan

**Comment by arturohernandez10** [comment]
________________________________

**Comment by arturohernandez10** [comment]
First, thank you so much for your response. This will be useful for me as I consider how to use prompt agent. I'm sure others will also benefit from reading it here in GitHub.

I think research in prompt optimization is important, because it is a kind of learning. In particular optimized prompts have several qualities that make them a good candidate for agent adaptation. It's a mouthful, and I am happy to give more details about why I think this is the case.

As a software developer I am interested in complex tasks. As it stands, prompt-agent provides very good results. And unless I am missing something, it's not straight forward to use it for complex open-ended tasks.

I think language translation is a good candidate for enabling complex tasks. The idea being that solutions become much simpler when phrased in the right language. Part of my hypothesis relies on the flexibility afforded by LLM's ability to use, create or derive ad-hoc domain specific languages. In my mind, the eureka research is a great example of the potential of DSL problem translation as part of an LLM AI process. While I understand the specifics of the problem leveraged by the eureka research, don't "translate" directly to any complex open ended task.

I'd like to extend some of the ideas in prompt agent to support a translation step. And potentially a way to compose multiple optimizations paths.

Thanks again for your response,

  *   AH

________________________________

**Comment by robinsonkwame** [comment]
Just want to comment that the direction of extending prompt engineering to complex open-ended tasks might be solved using a graph like approach. [Graph of Thought](https://github.com/spcl/graph-of-thoughts) has an approach involving tree-like path following, refinement and negating. One possible implementation here is to include PromptAgent as an operation within a Graph of Thought framework, to adapt PromptAgent for tree structured computation in complex open ended problems.
