### ISSUE TITLE
请教大佬问题

### ISSUE THREAD

**Issue by PKQ1688** [XinyuanWangCS/PromptAgent#10]
我想问一下datasats里面的数据集是如何构造的，我如果要在自己的任务上搞应该怎么处理

**Comment by XinyuanWangCS** [comment]
Hi, 

你需要按照task.py中这个函数的要求构造数据集：https://github.com/XinyuanWangCS/PromptAgent/blob/ab1984ebdb3798e1ad2845418694cbb95b3ab9c9/src/tasks/base_task.py#L96
在readme的后面大致介绍了如何添加新的task，在base_task.py中有函数的具体代码与说明。总的来说如果你的任务不符合当前已有的task，那么你需要写一个新的task继承base_task的类，然后修改几个函数：从模型的response中提取答案，从数据集的label中提取ground truth，恰当的方式比较二者来判断prediction是否正确。

**Comment by PKQ1688** [comment]
好的 感谢大佬，主要是生成类的任务如何做出判断，有没有比较好的建议

**Comment by XinyuanWangCS** [comment]
目前的task都是选择题，所以计算reward只需要比较answer和label是否一致（或者包含）就可以。对于生成类任务理论上answer和你的tasks的label是基本不可能一样的，如果你的目标是answer和ground truth label越接近越好，你可以用生成任务常用的metric，如GLUE，在cal_correct函数中，如果score大于某个阈值就认为它正确，否则不正确。在cal_metric函数中可以直接用这个metric的值作为reward（不需要判断阈值）。这只是一个简单的例子，需要具体情况具体分析，如果在你的任务中已经有了这样一个衡量生成质量的metric，那可以用已有的metric，这样更好。

**Comment by PKQ1688** [comment]
好的 谢谢

Xinyuan Wang ***@***.***> 于2024年6月10日周一 16:30写道：
