### ISSUE TITLE
Questions about feedback prompt used for gradient descent

### ISSUE THREAD

**Issue by jihyukkim-nlp** [XinyuanWangCS/PromptAgent#12]
Hello, I have some questions about the implementation of error feedback, more precisely differences between the implemented codes and the paper. 

While looking at codes, it seems the feedback for prompt optimization is given from **correct examples** for which the model produce correct predictions, not wrong predictions.

The prompt used for generating feedback is
```
ascend_gradient_prompt_tempelate = """
I'm writing prompts for a language model designed for a task.

My current prompt is:
{cur_prompt}

This prompt gets the following examples correct:
{example_string}

For each example, carefully examine each question and correct answer step by step, provide comprehensive and different reasons why the prompt leads to the correct answer. At last, based on all these reasons, summarize and list all the aspects that can improve the prompt.
""".strip()
```

The prompt used for reflecting the feedback is 
```
ascend_optimize_prompt_tempelate = """
I'm writing prompts for a language model designed for a task.

My current prompt is:
{cur_prompt}

This prompt gets the following examples correct:
{example_string}

Based on these examples, the advantages of this prompt and the reasons are:
{gradient}

There are a list of former prompts including the current prompt, and each prompt is modified from its former prompts:
{trajectory_prompts}

Based on the above information, please write {steps_per_gradient} new prompts following these guidelines:
1. The new prompts should solve the current prompt's problems.
2. The new prompts should consider the list of prompts and evolve based on the current prompt.
3. Each new prompt should be wrapped with <START> and <END>.

The new prompts are:
""".strip()
```

However, in the paper, it is written that we use failure examples with wrong predictions, and the feedback should discuss "why
the prompt leads to the **wrong answer**.", as written in the following prompt copied from the paper.
```
I’m writing prompts for a language model designed for a task.
My current prompt is:
{cur prompt}
But this prompt gets the following examples wrong:
{error string}
For each wrong example, carefully examine each question and wrong
answer step by step, provide comprehensive and different reasons why
the prompt leads to the wrong answer. At last, based on all these reasons, summarize and list all the aspects that can improve the prompt.
```

So, my questions are 

- I am wondering which one is actually used for the experiments reported in the paper. 
- Could you discuss motivation for this `ascend_gradient_prompt_tempelate` by any chance? This meta prompt seems also interesting as much as the error-feedback prompt!
- Have you see any different behaviors between the two prompts? 
- I am wondering if you have tried the mix of the two. How would it be if we use mix of successful examples and failure examples for the feedback?

**Comment by jihyukkim-nlp** [comment]
Oh, sorry for confusion. It seems the gradient "ascend" is invoked only when all examples are correct 😅

**Comment by XinyuanWangCS** [comment]
Hi, 

Thank you for closely reading our code. Your understanding is correct.

The "ascend" part is newly added because I discuss with other people in Github Issue #7. This is for a more robust system for the public to use rather than exactly follow the paper's method.
