### ISSUE TITLE
huggingface数据运行方式

### ISSUE THREAD

**Issue by Jade0321** [XinyuanWangCS/PromptAgent#13]
请问一下NCBI，Biosses，Med QA，TREC，CB这些领域知识相关的数据集上怎么运行实验？data_dir是写huggingface地址吗？另外我仔细看了看这些数据集，好些不是选择题，作者大大是改编了题目格式吗？

**Comment by XinyuanWangCS** [comment]
NCBI 是name entity recognition task，它的机制不是selection problem；Biosses原本是预测一个连续的值，我们把它离散化后变成了selection problem；MedQA，TREC，CB是选择题。data_dir只有当数据集是本地json文件是需要写，huggingface地址被写到了具体的task.py内部，如果要跑某个task你可以看一眼那个code，理论上修改一下yaml文件关于task的参数就好。（大部分Bigbench task共用一个task.py，通过data_dir决定是哪个task，其他的不能通用的bigbench task还有其他的task有自己的task.py）
