### ISSUE TITLE
一点小想法

### ISSUE THREAD

**Issue by PKQ1688** [XinyuanWangCS/PromptAgent#15]
大佬，能不能什么办法在输入的时候提供一定的先验知识，比如一些人工的case或者一些prompt的方法论。

**Comment by XinyuanWangCS** [comment]
可以再init prompt里加入你想要的信息，promptagent会在生产新prompt时考虑prompt trajectory，但是搜索深度越深，init prompt中的信息会越来越少。

**Comment by PKQ1688** [comment]
好的，谢谢。我在思考的是有没有办法把一些方法论的东西融入其中，来影响搜索的最终结果，比如CO-STAR框架这样的东西，是不是可以探索下，然后再整一篇论文啊，大佬哈哈哈。

**Comment by XinyuanWangCS** [comment]
哈哈谢谢。在生成时引入条件可以影响搜索，想要得到有效的prompt生成框架需要平衡搜索效果、效率和人的先验知识，这个需要很多实验。多谢讨论。
