### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Jade0321** [XinyuanWangCS/PromptAgent#4]
I followed the instructions in the README to run the PromptAgent code and encountered the following error:

```
 File "/PromptAgent/src/prompt_optim_agent/search_algo/beam_search.py", line 3, in <module>
    from .base_algo import SearchAlgo, State, Action
  File "/PromptAgent/src/prompt_optim_agent/search_algo/base_algo.py", line 7, in <module>
    Trace = tuple[list[State], list[Action]]
TypeError: 'type' object is not subscriptable
```
Did I not execute the code correctly somewhere?
However, I really like your work.

**Comment by XinyuanWangCS** [comment]
You may remove this line "Trace = tuple[list[State], list[Action]]". I think it is not used. Also, you may update your python to be higher or equal to 3.9 version.
