### ISSUE TITLE
rewards 数组为空怎么解决

### ISSUE THREAD

**Issue by huangzhenhao90** [XinyuanWangCS/PromptAgent#8]
大佬你好，非开发者，在尝试使用你的代码给文本进行多标签分类。因为我的标签集非常多，常规的人工 review 调优prompt比较耗精力，有幸找到您这篇论文。

参照您的相关代码，我创建了自己的数据集和 task.py，也在gpt的帮助下改了一些代码，在运行时，遇到以下的错误，gpt解释说是‘在你的 search_algo/mcts.py 文件中，simulate_choice 函数尝试对一个空的 rewards 数组进行操作，这通常发生在数组初始化不正确或者预期的数据没有被正确填充的情况下。’

作为编程初初初级学者，我不知道应该去哪个文件里查看 rewards 数据因为什么没有生成成功，斗胆请教～

报错如下：
`optimized_prompt:
[]

Traceback (most recent call last):
  File "/Users/huang/PromptAgent/src/main.py", line 67, in <module>
    main(args)
  File "/Users/huang/PromptAgent/src/main.py", line 62, in main
    agent.run(init_state=args['init_prompt'], iteration_num=args['iteration_num'])
  File "/Users/huang/PromptAgent/src/prompt_optim_agent/agent.py", line 129, in run
    states, result_dict = self.search_algo.search(init_state=init_state, iteration_num=iteration_num)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huang/PromptAgent/src/prompt_optim_agent/search_algo/mcts.py", line 346, in search
    path, cum_rewards = self.iterate(self.root)
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huang/PromptAgent/src/prompt_optim_agent/search_algo/mcts.py", line 325, in iterate
    self._simulate(path)
  File "/Users/huang/PromptAgent/src/prompt_optim_agent/search_algo/mcts.py", line 292, in _simulate
    node = node.children[self.simulate_choice(rewards)]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huang/PromptAgent/src/prompt_optim_agent/search_algo/mcts.py", line 137, in simulate_choice
    if rewards.size == 0:
       ^^^^^^^^^^^^`

----

我的 task文件代码：

# 导入必要的库和模块
from .base_task import BaseDataset, BaseTask
import re
import string

class CustomTask(BaseTask):
    def __init__(self, 
                 train_size, 
                 eval_size,
                 test_size=None,  
                 task_name="tutoring_services_classfication",
                 task_description="Classify the tutoring services based on feedback",
                 data_dir='',  
                 seed=None, 
                 post_instruction=True, 
                 TaskDataset=BaseDataset,
                 option_num=5,
                 **kwargs):
        super().__init__(
            task_name=task_name,  
            task_description=task_description, 
            data_dir=data_dir,
            seed=seed,
            train_size=train_size,
            eval_size=eval_size,
            test_size=test_size,
            post_instruction=post_instruction,
            TaskDataset=TaskDataset,
            option_num=option_num,
        )
        self.labels = [**_..省略.._**
        ]
        self.answer_format_prompt = ""

    def load_task_dataset(self, data_dir):
        '''
            <task specific>
        '''
        json_data = self._load_json_file(data_dir)
        self.task_description = json_data['description']
        return json_data
    
    def transform_format(self, data):
        original_examples = data['examples']

        examples = []
        # Extracting input and target scores
        for example in original_examples:
            question = example['input']
            answer = example['target']
            formatted_example = {
                'question': question,
                'answer': answer
            }
            examples.append(formatted_example)
        return examples

    def clean_response(self, response):
        return self.extract_keywords_from_response(response, self.labels)

    def extract_keywords_from_response(self, response, labels):
        pattern_str = '|'.join([re.escape(label) for label in labels])
        matches = re.findall(pattern_str, response, re.IGNORECASE)
        if matches:
            seen = set()
            unique_matches = [x for x in matches if not (x in seen or seen.add(x))]
            return ', '.join(unique_matches)
        else:
            return response

    def batch_clean_responses(self, responses):
        batch_answers = []
        for response in responses:
            cleaned_response = self.clean_response(response)
            batch_answers.append(cleaned_response)
        return batch_answers

**Comment by XinyuanWangCS** [comment]
你好，发一下你执行的命令。你可以使用最新的代码，改动了一些地方，可以更方便地输入命令，但对你写的task部分没有影响。

**Comment by huangzhenhao90** [comment]
> 你好，发一下你执行的命令。你可以使用最新的代码，改动了一些地方，可以更方便地输入命令，但对你写的task部分没有影响。

多谢，以下是我的执行命令🙏

python src/main.py --task_name tutoring_services_classification --search_algo mcts --batch_size 5 --depth_limit 5 --train_size 70 --eval_size 50 --test_size 50 --seed 42 --train_shuffle True --iteration_num 2 --expand_width 3 --post_instruction False --pred_model gpt-3.5-turbo --optim_model gpt-4 --log_dir logs/ --data_dir /Users/huang/PromptAgent/datasets/tutoring_services_classfication.json --init_prompt "我有很多用户填写在问卷里的主观反馈，请给每行的反馈打上标签。

## 输出格式：
- 请直接输出标签名称，如有多个标签，请用英文逗号分隔

标签如下

用户反馈如下：

" --api_key "sk-"

**Comment by XinyuanWangCS** [comment]
Hi 我认为你可以用我们最新的代码，新的代码对写task部分不影响，执行更方便。我看了你的task代码，如果理解正确每个question的答案是self.labels中的几个label。需要注意：

假设你每个question对应的ground-truth answer的格式是用逗号连接的几个labels，我认为比较prediction和answer的格式应该是两个set比较，这样比较与prediciton和answer中的label顺序无关。应该写的函数包括clean_labels（将ground-truth answer转为set），clean_response（从response中提取labels，转换为set），cal_correct（比较prediction set和ground-truth answer set），cal_metric（根据你实际任务需求，如果你的metric就是全部label相同算正确则与cal_correct相同，也可能使用F1 score等等）示例如下，你可能还需修改。（按照我的设定self.labels是一个list或者set，需要你确认一下）

`
def clean_labels(self, labels):
    result = []
    for input_str in labels:
        # 使用正则表达式将输入字符串按逗号和空格分割成词或短语
        words = re.split(r',\s*', input_str)
        # 提取存在于 self.labels 中的词或短语，并存储在集合中
        label_set = set(word for word in words if word in self.labels)
        result.append(label_set)
    return result

def clean_response(self, response):
    pattern = re.compile(r'\b(' + '|'.join(re.escape(label) for label in self.labels) + r')\b')
    labels_found = re.findall(pattern, response)
    label_set = set(labels_found)
    return label_set

def cal_correct(self, preds, labels):
    comparisons = []
    for p, l in zip(preds, labels):
        if p == l:
            comparisons.append(1)
        else:
            comparisons.append(0)
    return comparisons

def cal_metric(self, preds, labels, questions=None):
        '''
        <task specific>
        Calculate the evaluation metric, e.g. Accuracy, F1 score.
        return a number / tuple of metrics
        '''
        correct = self.cal_correct(preds=preds, labels=labels)
        return np.mean(correct)
`

你可以查看log文件中的记录观察模型的输出。如果有后续问题可以总结一下我们简单meeting一下解决。

**Comment by huangzhenhao90** [comment]
> Hi 我认为你可以用我们最新的代码，新的代码对写task部分不影响，执行更方便。我看了你的task代码，如果理解正确每个question的答案是self.labels中的几个label。需要注意：
> 
> 假设你每个question对应的ground-truth answer的格式是用逗号连接的几个labels，我认为比较prediction和answer的格式应该是两个set比较，这样比较与prediciton和answer中的label顺序无关。应该写的函数包括clean_labels（将ground-truth answer转为set），clean_response（从response中提取labels，转换为set），cal_correct（比较prediction set和ground-truth answer set），cal_metric（根据你实际任务需求，如果你的metric就是全部label相同算正确则与cal_correct相同，也可能使用F1 score等等）示例如下，你可能还需修改。（按照我的设定self.labels是一个list或者set，需要你确认一下）
> 
> ` def clean_labels(self, labels): result = [] for input_str in labels: # 使用正则表达式将输入字符串按逗号和空格分割成词或短语 words = re.split(r',\s*', input_str) # 提取存在于 self.labels 中的词或短语，并存储在集合中 label_set = set(word for word in words if word in self.labels) result.append(label_set) return result
> 
> def clean_response(self, response): pattern = re.compile(r'\b(' + '|'.join(re.escape(label) for label in self.labels) + r')\b') labels_found = re.findall(pattern, response) label_set = set(labels_found) return label_set
> 
> def cal_correct(self, preds, labels): comparisons = [] for p, l in zip(preds, labels): if p == l: comparisons.append(1) else: comparisons.append(0) return comparisons
> 
> def cal_metric(self, preds, labels, questions=None): ''' Calculate the evaluation metric, e.g. Accuracy, F1 score. return a number / tuple of metrics ''' correct = self.cal_correct(preds=preds, labels=labels) return np.mean(correct) `
> 
> 你可以查看log文件中的记录观察模型的输出。如果有后续问题可以总结一下我们简单meeting一下解决。

哇，太感谢啦，帮我看了代码还写了代码！你的理解是对的，「每个question的答案是self.labels中的几个label」。看上去问题出在对于准确率的计算上，如果这里计算有问题后边应该就有问题了。我用你们最新更新的项目代码和你写的代码赶快调试一下。再次感谢哇🙏

**Comment by huangzhenhao90** [comment]
> Hi 我认为你可以用我们最新的代码，新的代码对写task部分不影响，执行更方便。我看了你的task代码，如果理解正确每个question的答案是self.labels中的几个label。需要注意：
> 
> 假设你每个question对应的ground-truth answer的格式是用逗号连接的几个labels，我认为比较prediction和answer的格式应该是两个set比较，这样比较与prediciton和answer中的label顺序无关。应该写的函数包括clean_labels（将ground-truth answer转为set），clean_response（从response中提取labels，转换为set），cal_correct（比较prediction set和ground-truth answer set），cal_metric（根据你实际任务需求，如果你的metric就是全部label相同算正确则与cal_correct相同，也可能使用F1 score等等）示例如下，你可能还需修改。（按照我的设定self.labels是一个list或者set，需要你确认一下）
> 
> ` def clean_labels(self, labels): result = [] for input_str in labels: # 使用正则表达式将输入字符串按逗号和空格分割成词或短语 words = re.split(r',\s*', input_str) # 提取存在于 self.labels 中的词或短语，并存储在集合中 label_set = set(word for word in words if word in self.labels) result.append(label_set) return result
> 
> def clean_response(self, response): pattern = re.compile(r'\b(' + '|'.join(re.escape(label) for label in self.labels) + r')\b') labels_found = re.findall(pattern, response) label_set = set(labels_found) return label_set
> 
> def cal_correct(self, preds, labels): comparisons = [] for p, l in zip(preds, labels): if p == l: comparisons.append(1) else: comparisons.append(0) return comparisons
> 
> def cal_metric(self, preds, labels, questions=None): ''' Calculate the evaluation metric, e.g. Accuracy, F1 score. return a number / tuple of metrics ''' correct = self.cal_correct(preds=preds, labels=labels) return np.mean(correct) `
> 
> 你可以查看log文件中的记录观察模型的输出。如果有后续问题可以总结一下我们简单meeting一下解决。

修改了一下你的代码之后跑通啦，看到了 log 里的data.json！

不过感觉我当前的任务可能不适合这个框架呢（一些思考如下）：
- 一是因为我是一个多标签分类任务，在判断预测正确和错误的时候，不管是全对算正确还是有一个对就算正确，大模型在分析错误时好像都会有一些损失。
- 第二个是我的多标签是一个给定的集合（49 个标签），在初始 Prompt 中就要把这个标签集放进去，让大模型打标的时候从这个标签集中选择。在迭代 Prompt 的过程中，慢慢的这个标签集就从Prompt 中消失了，导致没有出来太好的优化 Prompt。不过我感觉在一些单标签的分类任务中应该会很有用，我会再多研究研究，为后边的任务做做准备。

再次感谢🙏

**Comment by XinyuanWangCS** [comment]
感谢使用。

1. “大模型在分析错误时好像都会有一些损失”：我同意，可能对于一个49个标签的问题对于LLM检查错误的原因难度比较高。

2. 这样的fixed的部分可以被加在self.answer_format_prompt，它会被加在task question最后面；或者在transform_format函数里面把dataset中每个question后面加上你的所有labels。E.g. question + "所有可能的标签是：[label0, ...]"

**Comment by huangzhenhao90** [comment]
> 感谢使用。
> 
> 1. “大模型在分析错误时好像都会有一些损失”：我同意，可能对于一个49个标签的问题对于LLM检查错误的原因难度比较高。
> 2. 这样的fixed的部分可以被加在self.answer_format_prompt，它会被加在task question最后面；或者在transform_format函数里面把dataset中每个question后面加上你的所有labels。E.g. question + "所有可能的标签是：[label0, ...]"

好嘞，你说的第二点里的方法我再试一下～～
