### ISSUE TITLE
initial prompt的设定

### ISSUE THREAD

**Issue by Jade0321** [XinyuanWangCS/PromptAgent#9]
除了penguins_in_a_table.json数据集，其他数据集的initial prompt请问如何设定？

**Comment by XinyuanWangCS** [comment]
对于BigBench中的task，我们一般使用.json文件中dataset自带的desciption项，例如：https://github.com/XinyuanWangCS/PromptAgent/blob/58b2435f47e925c9e324309e8b7988d548aed156/datasets/geometric_shapes.json#L4

对于其他数据集，我们观察数据集本身是否自带一个简单instruction或者描述，如果没有我们会人工写一个简单的描述这个task的prompt。initial prompt 通常可以是一个简单的，general的prompt，当然如果有很多的prior knowledge，也可以写一个复杂度initial prompt。

**Comment by Jade0321** [comment]
> 对于BigBench中的task，我们一般使用.json文件中dataset自带的desciption项，例如：
> 
> https://github.com/XinyuanWangCS/PromptAgent/blob/58b2435f47e925c9e324309e8b7988d548aed156/datasets/geometric_shapes.json#L4
> 
> 对于其他数据集，我们观察数据集本身是否自带一个简单instruction或者描述，如果没有我们会人工写一个简单的描述这个task的prompt。initial prompt 通常可以是一个简单的，general的prompt，当然如果有很多的prior knowledge，也可以写一个复杂度initial prompt。

好的，感谢~~~
